POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE5NjM4NDMsInN1YiI6ImNkODdkOGQ3LTEyZTktNGFiYy04ODM1LTY1MTlmZGFmYzdmNiJ9.WBcJzYm69ZILLSMwnTWrzgPhefQ4eQP6a_motFlUY8g

###

GET http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1
Content-Type: application/json

{
    "name": "Cadeira para escritório do pedro",
    "price": 1600
}

###
DELETE http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1