POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

GET http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1
Content-Type: application/json

{
    "name": "Cadeira para escritório do pedro",
    "price": 1600
}

###
DELETE http://localhost:8000/products/566ab788-8db8-4ba8-a50b-ace6be5ce203 HTTP/1.1