basePath: /
host: localhost:8080
info:
  contact:
    email: pedro@gutierres.com.br
    name: Pedro Gutierres
    url: https://www.linkedin.com/in/pedrogabrielgutierres/
  description: Product API with authentication
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
